Upgraded Exoplayer to Media3
ThePalaceProject/android-audiobook pull request #110
Opened 2023-11-28 19:02 UTC by nunommts

**What's this do?**
This PR upgrades the current ExoPlayer version to the most recent one, now called Media3. While the LCPAudiobookPlayer remained almost unchanged, there were some significant changes made to the ExoAudiobookPlayer. In addition to removing some unused/unnecessary code, there's been a change in the way the threads are created and handled. The Exoplayer itself hands the threads quite well, but for some reason, when we called the `prepare()` method for the ExoPlayer, the `STATE_READY` from Exoplayer was never called which caused the exoplayer's duration and current position to never be updated. In fact, the duration was returned as a huge negative number, which cause the app to crash when trying to convert it to a string with the remaining duration.

In order to fix this, the only way I found to make this properly work after trying an unhealthy amount of alternatives and possible solutions, was to do everything on the main thread. By doing this, the ExoPlayer wil internally handle that and call the `STATE_READY` when it's, in fact, ready. There's also a new flag to prevent the ExoPlayer's current position and duration from being accessed if the player is not ready.

**Why are we doing this? (w/ JIRA link if applicable)**
There's a [feature request](https://ebce-lyrasis.atlassian.net/browse/PP-713) to migrate the ExoPlayer version to the Media3

**How should this be tested? / Do these changes have associated tests?**
Open the Palace app
Select "LYRASIS Reads"
Open any audiobook
Start listening to it and perform some operations such as rewinding, forwarding, pause, play, select a chapter, etc.
Confirm everything's working correctly
Return and open the library selection
Select "Palace Marketplace Integration Library"
Open any audiobook (p.e. Stories of the Pilgrim, by Marget B. Pumphrey)
Start listening to it and perform some operations such as rewinding, forwarding, pause, play, select a chapter, etc.
Confirm everything's working correctly

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

2023-11-29 14:04 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
>        ).get(5L, SECONDS)
This leaks a thread every time an audio book is opened. Executors are resources that have to be shut down if they're not going to be used any further.

2023-11-29 14:05 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> -
I'm not clear on why `CountDownTimer` is necessary. It should be functionally identical to using a scheduled executor but with the advantage that it doesn't depend on any poor-quality Android API things...

2023-11-29 14:06 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> -    }
:fire:

2023-11-29 14:06 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
Not sure you meant to leave this in.

2023-11-29 14:07 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
>      }
`// // //` :laughing:

2023-11-29 14:08 UTC, io7m requested changes
May need some adjustments.

2023-11-29 14:32 UTC, nunommts commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
Nop, I've missed it while cleaning the PR

2023-11-29 14:34 UTC, nunommts commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> -
I don't know why, but the current PlaybackObserver running on the ScheduledExecutor wasn't being called. I think it had something to do with the threading changes I've made and I needed to use something with the same behavior. I can try using it again just to confirm.

2023-11-29 14:35 UTC, nunommts commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
>        ).get(5L, SECONDS)
Ok, I see. I'll try to make some adjustments on this. In the current code, is it being shutdown?

2023-11-29 15:40 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
>        ).get(5L, SECONDS)
In this case, the audio book player doesn't actually take ownership of the `ExecutorService`. You can see that it's passed in to the `create()` method as a parameter. I think that executor is created by the activity that hosts all of this stuff, and it's shut down when that activity goes away (yet another thing that needs to be replaced with stateful services!).

2023-11-29 15:42 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> -
I think it's important to really understand what's happening on what thread. Multi-threading really isn't something we can leave to chance... Multi-threading bugs can pop up after months of use, and are generally really nasty to track down.

2023-11-29 15:49 UTC, nunommts commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> -
I think we can sum things like this: for some reason, the ExoAudiobookPlayer player never reaches its `STATE_READY` when being set and getting its `prepare()` method called within the engineExecutor's thread. Because of this, the only way I found to make things work was to call everything from the main thread. If the exoplayer is accessed by a different thread than the one where it was created (in the main thread, in this case), it will handle it internally and throw an exception informing that it's being access from a different thread than expected.

2023-11-29 16:09 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
>        ).get(5L, SECONDS)
> yet another thing that needs to be replaced with stateful services!

Er, I don't mean that you need to replace that code now, to be clear! :sweat_smile: 

It's on the list of things I'm going to fix when the catalog is reimplemented.

2023-11-30 11:26 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> -
Is that because `CountDownTimer` always calls its callbacks on the main thread?

The documentation doesn't actually say it does, but... I assume it does.

2023-11-30 18:52 UTC, io7m commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> +      return Executors.newSingleThreadScheduledExecutor().submit(
Did you miss this one?

2023-11-30 19:14 UTC, nunommts commented on org.librarysimplified.audiobook.open_access/src/main/java/org/librarysimplified/audiobook/open_access/ExoAudioBookPlayer.kt
> +      return Executors.newSingleThreadScheduledExecutor().submit(
No, I haven't. I think you're looking at an outdated version of the file

2024-01-04 12:04 UTC, merged

2024-01-04 12:09 UTC, io7m commented
Turns out what happened with this was that the original threading behavior of ExoPlayer was "you must call methods on the player on the thread you used to create the player" to "you must create the player on a UI thread, and you must call methods on the same UI thread". This explains the behaviour you saw, and why it's now safe to work without an explicit engine thread.