Updated audiobook chapter/tracks downloading logic
ThePalaceProject/android-audiobook pull request #26
Opened 2022-05-02 17:32 UTC by nunommts

**What's this do?**
This PR updates the audiobook chapter/tracks downloading logic. Instead of having a download task associated to a spine item, now we have a list of spine items associated to a download task, so when it starts fetching, all of its associated spine items have their downloading status updated at the same time with the same value.

**Why are we doing this? (w/ JIRA link if applicable)**
There's a [feature request](https://www.notion.so/lyrasis/Update-audiobook-chapter-download-logic-acd3305e0ef147bd8478200cac96117a) to do this because in some audiobooks, some chapters have the same file with a different offset, so in this case the same file was being downloaded more than once, which could result in large waiting times for the user.

**How should this be tested? / Do these changes have associated tests?**
Open the sample player
Choose the "Flatland TOC" book
Open the TOC screen
Verify that there are ![some chapters being downloaded at the same time with the same status](https://user-images.githubusercontent.com/79104027/166295983-79c358b3-0e66-4676-b12b-53a3e8734a31.png)
Click on the loading animation of the first item and click on "Stop"
Verify [the first 4 tracks have stopped being downloaded](https://user-images.githubusercontent.com/79104027/166296041-ed1ec9e4-b2b6-40fe-9567-18048d0fa2ee.png)

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

2022-05-04 05:07 UTC, ray-lee requested changes
This mostly looks good. There are some comments/questions below.

Also, I think it's important to add a test for this functionality. The test should read in the Flatland TOC manifest (or a similar made-up one), and verify that each URL is fetched exactly once, through a mock HTTP client. I know it's a pain, but this is the kind of thing we can easily forget about and break in the future, if there isn't a test.

2022-05-04 15:47 UTC, nunommts commented on org.librarysimplified.audiobook.tests/src/main/java/org/librarysimplified/audiobook/tests/lcp/LCPEngineProviderContract.kt
> -
I didn't delete this. Actually, if I compare this file with the one from the _main_ branch, I don't see any changes. I'm not sure why this is happening because if I pull the main branch to this one, no changes occur.

2022-05-04 15:49 UTC, nunommts commented on org.librarysimplified.audiobook.tests/src/main/java/org/librarysimplified/audiobook/tests/open_access/ExoEngineProviderContract.kt
> +import org.librarysimplified.audiobook.api.*
I tried to prevent this in all files, but I missed this one!

2022-05-04 16:04 UTC, nunommts commented on org.librarysimplified.audiobook.tests/src/main/java/org/librarysimplified/audiobook/tests/open_access/ExoEngineProviderContract.kt
> +    book.downloadTasks.first().delete()
Yes, it was exactly an extra paste!

2022-05-04 16:08 UTC, nunommts commented
@ray-lee Sure, `fulfillsSpineElement` looks like a good option :)

2022-05-04 21:39 UTC, nunommts commented on org.librarysimplified.audiobook.views/src/main/java/org/librarysimplified/audiobook/views/PlayerTOCAdapter.kt
> +                task.spineItems.contains(item)
I can't because it's a method from the _ExoDownloadTask_ and not from the _PlayerDownloadTaskType_ interface. Do you want me to move it to the interface?

2022-05-05 11:49 UTC, nunommts commented on org.librarysimplified.audiobook.tests/src/main/java/org/librarysimplified/audiobook/tests/lcp/LCPEngineProviderContract.kt
> -
I still don't know how/why it was removed, but I've restored it.

2022-05-06 15:55 UTC, ray-lee commented on org.librarysimplified.audiobook.views/src/main/java/org/librarysimplified/audiobook/views/PlayerTOCAdapter.kt
> +                task.spineItems.contains(item)
Yes, since the `spineItems` property is in `PlayerDownloadTaskType`, I think it makes sense to have the `fulfillsSpineElement` method there too.

2022-05-13 14:42 UTC, ray-lee approved these changes
Looks good, thanks!

2022-05-13 14:42 UTC, merged