Target Android 12 (API 32).
ThePalaceProject/android-audiobook pull request #47
Opened 2022-10-20 04:25 UTC by ray-lee

**What's this do?**
[Description of what this PR does goes here]

**Why are we doing this? (w/ JIRA link if applicable)**
[Quick blurb about why the code is needed and Jira link goes here / Do these changes meet the business requirements of the story?]

**How should this be tested? / Do these changes have associated tests?**
[Description of any tests that need to be performed once merged goes here]

**Dependencies for merging? Releasing to production?**
[Description of any watchouts, dependencies, or issues we should be aware of goes here]

**Have you updated the changelog?**

**Has the application documentation been updated for these changes?**

**Did someone actually run this code to verify it works?**

2022-10-20 10:45 UTC, nunommts requested changes

2022-10-20 10:45 UTC, nunommts commented on org.librarysimplified.audiobook.views/src/main/java/org/librarysimplified/audiobook/views/PlayerService.kt
>      )
Since this immutable flag is only required for the API 23+ and we support the API 21, I think it would be better to add this to all of these intents

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
      } else {
        PendingIntent.FLAG_UPDATE_CURRENT
      }
```

2022-10-26 16:34 UTC, ray-lee commented on org.librarysimplified.audiobook.views/src/main/java/org/librarysimplified/audiobook/views/PlayerService.kt
>      )
Yes, good catch. This is fixed.

2022-10-26 22:22 UTC, nunommts approved these changes

2022-10-27 01:13 UTC, merged