Updated audiobook player to support new Audible TOC
ThePalaceProject/android-audiobook pull request #52
Opened 2022-11-29 12:47 UTC by nunommts

**What's this do?**
This PR updates the logic to handle manifests with both `toc` and `readingOrder` objects in order to update the app to support the new Audible TOC format.

**Why are we doing this? (w/ JIRA link if applicable)**
There's a [ticket](https://www.notion.so/lyrasis/Update-Android-audiobook-player-to-support-Audible-TOC-0307c14b2f404b708d5744e6473d3187) saying the Audible has a new TOC format and the apps should be updated to match the new requirements.

**How should this be tested? / Do these changes have associated tests?**
Open the Palace app
Select "LYRASIS Reads" library
Search for the audiobook "Anna Karenina" by Leo Tolstoy
Play the audiobook
Open the TOC and confirm the [chapters information is there without a reference to "Part X"](https://user-images.githubusercontent.com/79104027/204532866-2abf9a23-fae6-4a30-9156-9644e752ceed.png)

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

2022-11-30 16:50 UTC, ray-lee requested changes
@nunommts There is a failing test. Also, could you add a test that uses the Anna Karenina manifest, and shows what is expected? That will help me to understand what this does.

2022-11-30 17:12 UTC, nunommts commented
@ray-lee That's exactly what I'm trying to do right now, but I'm facing some issues while trying to run the tests. I'll update the PR when I fix them.

2023-03-31 02:48 UTC, ray-lee reviewed
This looks very good. I just noticed a few small things. 

Also (not relevant to this PR), does the player in android-drm-audioengine need to be updated?

2023-03-31 02:48 UTC, ray-lee commented on org.librarysimplified.audiobook.lcp/src/main/java/org/librarysimplified/audiobook/lcp/LCPAudioBookPlayer.kt
> +      // the offset is fewer than 0, so we need to get the next track
I think you mean "get the previous track".

2023-03-31 02:48 UTC, ray-lee commented on org.librarysimplified.audiobook.lcp/src/main/java/org/librarysimplified/audiobook/lcp/LCPAudioBookPlayer.kt
> +  private fun checkIfTrackHasChanged(
I think this function name is somewhat misleading. To me a "check" function returns a boolean depending on a condition, or possibly throws an exception if a condition isn't met. The main purpose of this function seems to be to update `trackIndex` (and optionally to seek to a position, and optionally start playing). How about naming it `updateTrackIndex`?

2023-03-31 09:04 UTC, nunommts commented on org.librarysimplified.audiobook.lcp/src/main/java/org/librarysimplified/audiobook/lcp/LCPAudioBookPlayer.kt
> +      // the offset is fewer than 0, so we need to get the next track
You're right! Thanks for noticing

2023-03-31 09:18 UTC, nunommts commented on org.librarysimplified.audiobook.api/src/main/java/org/librarysimplified/audiobook/api/PlayerPosition.kt
> +  val currentOffset: Long
Done. Please let me know if it's good.

2023-03-31 09:19 UTC, nunommts commented
@ray-lee Good call! Yes, it does. I'll update it and create a PR.

2023-03-31 15:20 UTC, ray-lee approved these changes
Looks good!

2023-03-31 15:33 UTC, ray-lee commented
@nunommts One more thing: This changes the API of PlayerPosition in a way that is not backward compatible, so it should be a major version upgrade. Could you change the version to 10.0.0-SNAPSHOT? Update it in the changelog too.

2023-03-31 19:18 UTC, ray-lee approved these changes
Looks good!

2023-04-03 08:35 UTC, merged