Added sleep timer to player fragment parameters
ThePalaceProject/android-audiobook pull request #54
Opened 2023-01-12 13:01 UTC by nunommts

**What's this do?**
This PR adds a sleep timer configuration to the player fragment parameters. It also updates the location of the existing sleeping timer values so the Palace main module can have access to them.

**Why are we doing this? (w/ JIRA link if applicable)**
There's a [feature request](https://www.notion.so/lyrasis/Audiobook-sleep-timer-not-saved-after-closing-book-bab815834a374893a0588ca96fc8caa7) saying the sleep timer is not being restored when the user sets it and closes and reopens the book.

**How should this be tested? / Do these changes have associated tests?**
This can only be tested when this PR is merged:

Open the Palace app
Open the any audiobook
Set a sleep timer
Close the audiobook
Reopen the audiobook
Confirm the sleep timer is the same you set

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

2023-01-12 20:14 UTC, ray-lee requested changes
This looks good, but it will require a major version bump. See below comment.

2023-01-12 20:14 UTC, ray-lee commented on gradle.properties
> +VERSION_PREVIOUS=7.0.1
This actually should be a major version bump. You added `onPlayerSleepTimerUpdated` to the `PlayerFragmentListenerType` interface, which is a breaking change to the API. Any classes that implement that interface will need to add `onPlayerSleepTimerUpdated`.

That means that `VERSION_PREVIOUS` can stay at `8.0.2`, but `VERSION_NAME` should become `9.0.0-SNAPSHOT`. Also the version number in will need to be changed to `9.0.0` in README-CHANGES.xml.

2023-01-12 22:02 UTC, nunommts commented
@ray-lee Sure, that makes sense! I had to move the file to the api folder so we can have access it on the Palace app without having to import the "views" from the Audiobook submodule. I can also do that, if you prefer.

2023-01-12 22:14 UTC, ray-lee commented
Yes, I think it makes sense to have it in the api folder.

2023-01-13 10:27 UTC, nunommts commented
@ray-lee I've updated the PR

2023-01-13 15:49 UTC, ray-lee requested changes
This is close, but the version numbers aren't quite right.

2023-01-13 15:49 UTC, ray-lee commented on gradle.properties
> +VERSION_NAME=9.0.0
This should be `9.0.0-SNAPSHOT`, since 9.0.0 is still under development.

2023-01-13 15:49 UTC, ray-lee commented on gradle.properties
> +VERSION_PREVIOUS=8.0.3-SNAPSHOT
This is supposed to be the last released version, which would be `8.0.2`.

2023-01-13 15:49 UTC, ray-lee commented on README-CHANGES.xml
> +    <c:release date="2023-01-12T11:58:45+00:00" is-open="true" ticket-system="org.nypl.jira" version="8.0.3">
The version here should be changed to `9.0.0`.

2023-01-13 17:13 UTC, ray-lee approved these changes
Looks good!

2023-01-13 17:13 UTC, merged